# -*- coding: utf-8 -*-
"""
job_generator.py — HPC job script generator for gstd TUI.

Supports SLURM (#SBATCH) and PBS/LSF (#PBS) schedulers.
The generated shell script activates a conda environment and runs the exact
gstd CLI command derived from the user's TUI settings.

──────────────────────────────────────────────────────────────────────────────
Usage
──────────────────────────────────────────────────────────────────────────────
    from genome_standardizer.tui.job_generator import HpcJobParams, generate_script

    job = HpcJobParams(
        scheduler    = "slurm",
        job_name     = "gstd_wheat",
        partition    = "large_mem",
        nodes        = 1,
        cpus         = 16,
        mem_gb       = 128,
        walltime     = "24:00:00",
        conda_env    = "core_dev",
        work_dir     = "/scratch/user/wheat",
        output_log   = "/scratch/user/gstd_%j.log",
        gff          = "annotation.gff3.gz",
        fasta        = "genome.fasta.gz",
        prefix       = "Trit_aest",
        extra_flags  = "--low-mem --longest --save-log",
    )
    script_text = generate_script(job)
    print(script_text)
"""

from dataclasses import dataclass, field
from typing import Optional


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class HpcJobParams:
    """
    All parameters needed to generate an HPC job submission script.

    The TUI collects these from its Job Script tab widgets and passes the
    populated dataclass to generate_script().
    """
    # Scheduler selection
    scheduler:   str   = "slurm"      # "slurm" or "pbs"

    # Job metadata
    job_name:    str   = "gstd_run"
    partition:   str   = "normal"      # SLURM: --partition / PBS: -q
    nodes:       int   = 1
    cpus:        int   = 8             # CPUs per task / PPN
    mem_gb:      int   = 32            # memory in GB
    walltime:    str   = "12:00:00"    # HH:MM:SS

    # Environment
    conda_env:   str   = "core_dev"
    work_dir:    str   = "/scratch/user/project"
    output_log:  str   = "gstd_%j.log"  # %j = job ID (SLURM); $PBS_JOBID for PBS

    # gstd command components
    gff:         str   = ""            # comma-separated for polyploids
    fasta:       str   = ""
    prefix:      str   = ""
    extra_flags: str   = ""            # e.g. "--low-mem --longest --save-log"

    # Optional email notification (leave empty to omit)
    email:       str   = ""
    email_type:  str   = "END,FAIL"   # SLURM mail-type / PBS mail-options


# ── Public entry point ────────────────────────────────────────────────────────

def generate_script(job: HpcJobParams) -> str:
    """
    Dispatch to the appropriate scheduler-specific generator.

    Args:
        job: Populated HpcJobParams dataclass.

    Returns:
        Complete shell script as a string.

    Raises:
        ValueError: If job.scheduler is not "slurm" or "pbs".
    """
    scheduler = job.scheduler.lower().strip()
    if scheduler == "slurm":
        return _generate_slurm(job)
    elif scheduler in ("pbs", "lsf"):
        return _generate_pbs(job)
    else:
        raise ValueError(
            f"Unknown scheduler '{job.scheduler}'. "
            "Supported values: 'slurm', 'pbs'."
        )


# ── SLURM generator ───────────────────────────────────────────────────────────

def _generate_slurm(job: HpcJobParams) -> str:
    lines = [
        "#!/bin/bash",
        "# ── SLURM Job Script — generated by gstd TUI ─────────────────────",
        "#",
        f"#SBATCH --job-name={job.job_name}",
        f"#SBATCH --partition={job.partition}",
        f"#SBATCH --nodes={job.nodes}",
        f"#SBATCH --ntasks=1",
        f"#SBATCH --cpus-per-task={job.cpus}",
        f"#SBATCH --mem={job.mem_gb}G",
        f"#SBATCH --time={job.walltime}",
        f"#SBATCH --output={job.output_log}",
        f"#SBATCH --error={job.output_log.replace('%j', '%j.err')}",
    ]

    if job.email:
        lines += [
            f"#SBATCH --mail-user={job.email}",
            f"#SBATCH --mail-type={job.email_type}",
        ]

    lines += [
        "#",
        "# ── Environment setup ───────────────────────────────────────────────",
        "set -euo pipefail",
        "",
        "# Load conda — adjust path if needed",
        "source \"$(conda info --base)/etc/profile.d/conda.sh\"",
        f"conda activate {job.conda_env}",
        "",
        "# ── Change to working directory ─────────────────────────────────────",
        f"cd \"{job.work_dir}\"",
        "",
        "# ── Run gstd ────────────────────────────────────────────────────────",
        _build_gstd_cmd(job),
        "",
        "echo \"[gstd] Job completed: $(date)\"",
    ]
    return "\n".join(lines) + "\n"


# ── PBS / LSF generator ───────────────────────────────────────────────────────

def _generate_pbs(job: HpcJobParams) -> str:
    # PBS walltime uses the same HH:MM:SS format; mem uses 'gb' suffix
    lines = [
        "#!/bin/bash",
        "# ── PBS/LSF Job Script — generated by gstd TUI ──────────────────────",
        "#",
        f"#PBS -N {job.job_name}",
        f"#PBS -q {job.partition}",
        f"#PBS -l nodes={job.nodes}:ppn={job.cpus}",
        f"#PBS -l mem={job.mem_gb}gb",
        f"#PBS -l walltime={job.walltime}",
        f"#PBS -o {job.output_log.replace('%j', '$PBS_JOBID')}",
        f"#PBS -e {job.output_log.replace('%j', '$PBS_JOBID')}.err",
    ]

    if job.email:
        lines += [
            f"#PBS -M {job.email}",
            f"#PBS -m {_pbs_mail_options(job.email_type)}",
        ]

    lines += [
        "#",
        "# ── Environment setup ───────────────────────────────────────────────",
        "set -euo pipefail",
        "",
        "# Load conda — adjust path if needed",
        "source \"$(conda info --base)/etc/profile.d/conda.sh\"",
        f"conda activate {job.conda_env}",
        "",
        "# ── Change to working directory ─────────────────────────────────────",
        f"cd \"{job.work_dir}\"",
        "",
        "# ── Run gstd ────────────────────────────────────────────────────────",
        _build_gstd_cmd(job),
        "",
        "echo \"[gstd] Job completed: $(date)\"",
    ]
    return "\n".join(lines) + "\n"


# ── Shared helpers ────────────────────────────────────────────────────────────

def _build_gstd_cmd(job: HpcJobParams) -> str:
    """Build the gstd CLI invocation from job parameters."""
    parts = ["gstd"]

    # Positional arguments
    parts.append(f'"{job.gff}"')
    parts.append(f'"{job.fasta}"')
    parts.append(f'"{job.prefix}"')

    # Extra flags (already formatted as a CLI string, e.g. "--low-mem --longest")
    if job.extra_flags.strip():
        parts.append(job.extra_flags.strip())

    # Always add --save-log in HPC mode for auditability (if not already present)
    if "--save-log" not in (job.extra_flags or ""):
        parts.append("--save-log")

    return " \\\n  ".join(parts)


def _pbs_mail_options(email_type: str) -> str:
    """Convert SLURM mail-type string to PBS -m option letters."""
    # SLURM: BEGIN, END, FAIL, ALL → PBS: b, e, a
    mapping = {"BEGIN": "b", "END": "e", "FAIL": "a", "ALL": "abe"}
    parts   = [p.strip().upper() for p in email_type.split(",")]
    pbs_opts = []
    for p in parts:
        if p in mapping:
            pbs_opts.append(mapping[p])
        elif p == "ALL":
            return "abe"
    # Deduplicate while preserving order
    seen, result = set(), []
    for c in "".join(pbs_opts):
        if c not in seen:
            seen.add(c)
            result.append(c)
    return "".join(result) or "n"   # "n" = no mail if nothing matched
